# action.yml
name: 'Spanner Hammer'
author: 'curi1119'
description: 'Run hammer for Google Cloud Spanner on Github Actions.'
inputs:
  hammer_ver:
    description: 'hammer version'
    required: false
    default: '0.5.7'
  hammer_cmd:
    description: 'create, diff or apply'
    required: true
    default: 'diff'
  schema:
    description: 'Local schema'
    required: true
    default: 'schema.sql'
  project_id: 
    description: 'Your Goolge ProjectId'
    required: true
    default: 'project_id'
  instance_id:
    description: 'Your Spanner InstancdId'
    required: true
    default: 'instance_id'
  database_id: 
    description: 'Your Spanner DatabaseId'
    required: true
    default: 'instance_id'
  google_application_credentials:
    description: 'GOOGLE_APPLICATION_CREDENTIALS(not file path)'
    required: false
    default: ''
  use_emulator:
    description: 'true if targeting spanner-emulator'
    required: false
    default: 'false'
  emulator_host:
    description: 'spanner-emulator host'
    required: false
    default: 'localhost:9010'

outputs:
  result:
    description: ''

branding:
  icon: 'check-circle'
  color: 'orange'
  
runs:
  using: composite
  steps:
    - run: ./entrypoint.sh
      shell: bash
      env:
        HAMMER_VER: ${{ inputs.hammer_ver }}
        HAMMER_CMD: ${{ inputs.hammer_cmd }}
        SCHEMA: ${{ inputs.schema }}
        PROJECT_ID: ${{ inputs.project_id }}
        INSTANCE_ID: ${{ inputs.instance_id }}
        DATABASE_ID: ${{ inputs.database_id }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ inputs.google_application_credentials }}
        USE_EMULATOR: ${{ inputs.use_emulator }}
        EMULATOR_HOST: ${{ inputs.emulator_host }}
