# action.yml
name: 'Spanner Hammer'
author: 'curi1119'
description: 'Run hammer for Google Cloud Spanner on Github Actions.'
inputs:
  hammer_ver:
    description: 'hammer version'
    required: false
    default: '0.5.7'
  hammer_cmd:
    description: 'create, diff or apply'
    required: true
    default: 'diff'
  schema:
    description: 'Local schema'
    required: true
    default: 'schema.sql'
  project_id: 
    description: 'Your Goolge ProjectId'
    required: true
    default: 'project_id'
  instance_id:
    description: 'Your Spanner InstancdId'
    required: true
    default: 'instance_id'
  database_id: 
    description: 'Your Spanner DatabaseId'
    required: true
    default: 'instance_id'
  google_application_credentials:
    description: 'GOOGLE_APPLICATION_CREDENTIALS(not file path)'
    required: false
    default: ''
  use_emulator:
    description: 'true if targeting spanner-emulator'
    required: false
    default: 'false'
  emulator_host:
    description: 'spanner-emulator host'
    required: false
    default: 'localhost:9010'

outputs:
  result:
    description: ''

branding:
  icon: 'check-circle'
  color: 'orange'

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        curl -OL https://github.com/daichirata/hammer/releases/download/v${HAMMER_VER}/hammer-${HAMMER_VER}-linux-amd64.tar.gz
        tar xzvf hammer-${HAMMER_VER}-linux-amd64.tar.gz
        mv hammer-${HAMMER_VER}-linux-amd64/hammer ./hammer
        chmod +x ./hammer
        rm -rf hammer-*

        url=spanner://projects/$PROJECT_ID/instances/$INSTANCE_ID/databases/$DATABASE_ID

        if [ "$USE_EMULATOR" = "true" ]; then
          export SPANNER_EMULATOR_HOST=$EMULATOR_HOST
          echo SPANNER_EMULATOR_HOST exported: "$SPANNER_EMULATOR_HOST"
        fi

        if [ $GOOGLE_APPLICATION_CREDENTIALS ]; then
          echo $GOOGLE_APPLICATION_CREDENTIALS > creds.json
          url=$url?credentials=creds.json
        fi
        echo url: $url
        echo cmd: $HAMMER_CMD

        ./hammer $HAMMER_CMD $url $SCHEMA
      env:
        HAMMER_VER: ${{ inputs.hammer_ver }}
        HAMMER_CMD: ${{ inputs.hammer_cmd }}
        SCHEMA: ${{ inputs.schema }}
        PROJECT_ID: ${{ inputs.project_id }}
        INSTANCE_ID: ${{ inputs.instance_id }}
        DATABASE_ID: ${{ inputs.database_id }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ inputs.google_application_credentials }}
        USE_EMULATOR: ${{ inputs.use_emulator }}
        EMULATOR_HOST: ${{ inputs.emulator_host }}
